services:
    db:
        image: postgres:16
        container_name: kanban-db
        environment:
            POSTGRES_USER: kanban_admin
            POSTGRES_PASSWORD: senha@123
            POSTGRES_DB: kanban
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: {}